# Generated by Django 5.1.3 on 2025-01-10 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailerphoto',
            name='created_at',
        ),
    ]
