# Generated by Django 4.2 on 2025-01-10 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0001_initial'),
        ('retailer', '0002_remove_retailerphoto_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='wholesale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wholesales.wholesale'),
        ),
    ]
