# Generated by Django 4.2 on 2025-01-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0003_retailer_wholesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerphoto',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
