# Generated by Django 4.2 on 2025-01-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0004_retailerphoto_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerphoto',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='retailerphoto',
            name='verified_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
