# Generated by Django 4.2 on 2025-01-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0005_retailerphoto_remarks_retailerphoto_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='kelurahan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='kota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
