# Generated by Django 4.2 on 2025-01-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0006_retailer_kecamatan_retailer_kelurahan_retailer_kota'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='provinsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
