# Generated by Django 4.2 on 2025-01-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0007_retailer_provinsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='expired_at',
            field=models.DateTimeField(default='2025-07-03 23:59:59'),
        ),
    ]
