# Generated by Django 4.2 on 2025-01-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0008_voucher_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
