# Generated by Django 4.2 on 2025-02-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0010_alter_retailerphoto_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
