# Generated by Django 4.2 on 2025-02-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0011_voucher_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerphoto',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
