# Generated by Django 4.2 on 2025-02-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0012_retailerphoto_is_rejected_voucher_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerphoto',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retailerphoto',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
