# Generated by Django 4.2 on 2025-07-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0019_voucherproject_voucherretailerdiscount_and_more'),
        ('retailer', '0013_retailerphoto_approved_at_retailerphoto_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.voucherproject'),
        ),
    ]
