"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from rest_framework.settings import api_settings
from storages.backends.s3boto3 import S3Boto3Storage
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Gunakan AWS S3 untuk menyimpan media files
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'on')

ALLOWED_HOSTS = ['localhost', 
                 '127.0.0.1', 
                 '0.0.0.0',
                 '10.0.63.158',  # Local network IP for development 
                 'apiryo.localhost',     # ✅ ADD: Backend domain localhost
                 'ryo.localhost',        # ✅ ADD: Frontend domain localhost
                 'apiryo.kcsi.id',  # Backend domain
                 'ryo.kcsi.id',     # Allow frontend domain for admin access
                 'kcsi-alb-prod-1476414350.ap-southeast-3.elb.amazonaws.com',
                 '.amazonaws.com',  # ← Wildcard untuk semua AWS domains
                 '.kcsi.id',        # ← Wildcard untuk domain kcsi.id
            ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'storages', #django-storages
    'api',
    'corsheaders',
    'office',
    'retailer',
    'wholesales',
    'rest_framework',
    'dj_rest_auth',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
]

MIDDLEWARE = [
    # 'core.middleware.ALBCORSMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

# AWS ALB Configuration
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CORS_ALLOW_ALL_ORIGINS = False  # Disable this if you want to restrict origins
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5174",
    "http://localhost:8000",
    "http://localhost:3000",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:3000",
    
    # Localhost domains
    "http://ryo.localhost",        # ✅ ADD: Frontend localhost domain
    "http://apiryo.localhost",     # ✅ ADD: Backend localhost domain

    # Production domains
    "http://ryo.kcsi.id",
    "https://ryo.kcsi.id",
    "http://apiryo.kcsi.id",
    "https://apiryo.kcsi.id",
    
    # ALB domains - Add semua kemungkinan
    "http://kcsi-alb-prod-1476414350.ap-southeast-3.elb.amazonaws.com",
    "http://kcsi-alb-prod-1476414350.ap-southeast-3.elb.amazonaws.com:8080",
    "http://kcsi-alb-prod-1476414350.ap-southeast-3.elb.amazonaws.com:8082",
    "https://kcsi-alb-prod-1476414350.ap-southeast-3.elb.amazonaws.com",
    "https://kcsi-alb-prod-1476414350.ap-southeast-3.elb.amazonaws.com:8080",
    "https://kcsi-alb-prod-1476414350.ap-southeast-3.elb.amazonaws.com:8082",
]

CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "DELETE", "OPTIONS","PATCH"]
CORS_ALLOW_HEADERS = ["*"]
CORS_ALLOW_CREDENTIALS = False  # Jika menggunakan cookies atau session
CORS_PREFLIGHT_MAX_AGE = 86400

# CSRF settings for cross-domain
CSRF_TRUSTED_ORIGINS = [
    "http://ryo.kcsi.id",
    "http://apiryo.kcsi.id",
    "https://ryo.kcsi.id",
    "https://apiryo.kcsi.id",
    "http://ryo.localhost",
    "http://apiryo.localhost",
    "http://kcsi-alb-prod-1476414350.ap-southeast-3.elb.amazonaws.com",  # ← Add ALB
    "https://kcsi-alb-prod-1476414350.ap-southeast-3.elb.amazonaws.com", # ← Add ALB HTTPS
]

AUTH_USER_MODEL = 'office.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.postgresql',
         'NAME': os.getenv('PSQL_NAME', 'dbname'),
         'USER': os.getenv('PSQL_USER', 'dbuser'),
         'PASSWORD': os.getenv('PSQL_PASSWORD', 'dbpassword'),
         'HOST': os.getenv('PSQL_HOST', 'dbhost'),
         'PORT': os.getenv('PSQL_PORT', '5432'),
         'OPTIONS': {
             'connect_timeout': 10,
         }
     } 
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = False

# AWS S3 Configuration - Fixed for ACL issue
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'ap-southeast-3')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# ✅ FIX: Disable ACL to avoid permission issues
AWS_DEFAULT_ACL = None
AWS_S3_FILE_OVERWRITE = False
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400'
}

# Additional settings
AWS_S3_ADDRESSING_STYLE = 'virtual'
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_QUERYSTRING_AUTH = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# HTTPS/SSL Settings (sesuaikan dengan environment)
if not DEBUG:
    # Production security settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = False  # Set True jika menggunakan HTTPS
    SESSION_COOKIE_SECURE = False  # Set True jika menggunakan HTTPS
    CSRF_COOKIE_SECURE = False     # Set True jika menggunakan HTTPS
    X_FRAME_OPTIONS = 'DENY'
else:
    # Development settings
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    X_FRAME_OPTIONS = 'SAMEORIGIN'

# Security settings (HTTP mode)
SECURE_PROXY_SSL_HEADER = None
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Admin security
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/staticfiles/'

# Additional directories for staticfiles
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
] if os.path.exists(os.path.join(BASE_DIR, 'static')) else []

# Static files finders
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]


# Media files for local development (when not using S3)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = 'media/'
MEDIA_URL = f'{AWS_S3_CUSTOM_DOMAIN}/' if AWS_STORAGE_BUCKET_NAME else '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

# Configure JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=120),  # Duration for access tokens
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # Duration for refresh tokens
    'ROTATE_REFRESH_TOKENS': True,                    # Rotate refresh tokens after each use
    'BLACKLIST_AFTER_ROTATION': True,                 # Blacklist old refresh tokens
}

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
