"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from rest_framework.settings import api_settings
from storages.backends.s3boto3 import S3Boto3Storage
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Gunakan AWS S3 untuk menyimpan media files
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'on')

SUB_PATH = os.getenv('SUB_PATH', '')
USE_KONG = os.getenv('USE_KONG', 'false').lower() == 'true'
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development')

hostname = os.getenv('HOSTNAME', '')
is_production = os.getenv('ENVIRONMENT', 'development') == 'production'
is_kong_environment = 'kcsi.id' in hostname or os.getenv('USE_KONG', 'false').lower() == 'true'

# FORCE_SCRIPT_NAME = basePath untuk URL generation dan OpenAPI schema (Swagger).
# Wajib di-set saat app diakses via prefix (e.g. api.kcsi.id/ryo-api/) agar curl di Swagger hit /ryo-api/api/login/.
_sub_path_normalized = (SUB_PATH or '').strip().strip('/')
if _sub_path_normalized:
    FORCE_SCRIPT_NAME = f'/{_sub_path_normalized}'
    KONG_SUB_PATH = SUB_PATH
    print(f"FORCE_SCRIPT_NAME={FORCE_SCRIPT_NAME} (basePath for Swagger & reverse URLs)")
else:
    FORCE_SCRIPT_NAME = None
    KONG_SUB_PATH = None
    print("FORCE_SCRIPT_NAME disabled (no SUB_PATH)")

# Debug output
print(f"DEBUG: {DEBUG}")
print(f"SUB_PATH: {SUB_PATH}")
print(f"USE_KONG: {USE_KONG}")
print(f"ENVIRONMENT: {ENVIRONMENT}")
print(f"FORCE_SCRIPT_NAME: {FORCE_SCRIPT_NAME}")

# Django membandingkan Host header lengkap (termasuk port). Sertakan localhost:9002 (backend) dan localhost:8000 (Kong).
_default_allowed = [
    'localhost', 'localhost:9002', 'localhost:8000', '127.0.0.1', '0.0.0.0', '10.0.63.158',
    'apiryo.localhost', 'ryo.localhost', 'apiryo.kcsi.id', 'backend-ryo',
    'api.kcsi.id', 'ryo.kcsi.id',
    'kcsi-alb-prod-1476414350.ap-southeast-3.elb.amazonaws.com', '.amazonaws.com', '.kcsi.id',
]
_raw_hosts = os.getenv('ALLOWED_HOSTS', '').strip()
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts.split(',') if h.strip()] if _raw_hosts else _default_allowed
# Selalu izinkan akses langsung backend (9002) dan via Kong (8000) agar /docs/ tidak 400
for _h in ('localhost:9002', 'localhost:8000'):
    if _h not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_h)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'storages', #django-storages
    'api',
    'corsheaders',
    'office',
    'retailer',
    'wholesales',
    'rest_framework',
    'dj_rest_auth',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
]

MIDDLEWARE = [
    'core.middleware.KongProxyMiddleware',  # Add Kong proxy middleware first
    # 'core.middleware.ALBCORSMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

# URL configuration to prevent 301 redirects
APPEND_SLASH = False  # Disable automatic trailing slash redirects
PREPEND_WWW = False   # Disable www prefix redirects

# AWS ALB Configuration
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
USE_X_FORWARDED_FOR = True

# Trust ALB headers for proper URL generation (agar request dianggap HTTPS)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Allow ALB health checks and internal communication
ALLOWED_CIDR_NETS = ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16']

CORS_ALLOW_ALL_ORIGINS = False
# Sertakan https://api.kcsi.id agar request dari Swagger (Try it out) di docs tidak kena CORS
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') or [
    "http://localhost:5174", "http://localhost:8080", "http://localhost:3000", "http://localhost:9002",
    "http://api.kcsi.id", "https://api.kcsi.id",
    "http://ryo.localhost", "http://apiryo.localhost",
    "http://ryo.kcsi.id", "https://ryo.kcsi.id", "http://apiryo.kcsi.id", "https://apiryo.kcsi.id",
]
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
CORS_ALLOW_HEADERS = ["*"]
CORS_ALLOW_CREDENTIALS = False
CORS_PREFLIGHT_MAX_AGE = 86400
CORS_EXPOSE_HEADERS = ["Content-Type", "Authorization"]

# CSRF settings for cross-domain
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') or [
    "http://api.kcsi.id",           # ✅ ADD: API Gateway HTTP
    "https://api.kcsi.id",          # ✅ ADD: API Gateway HTTPS
    "http://ryo.kcsi.id",
    "http://apiryo.kcsi.id",
    "https://ryo.kcsi.id",
    "https://apiryo.kcsi.id",
    "http://ryo.localhost",
    "http://apiryo.localhost",
]

AUTH_USER_MODEL = 'office.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.postgresql',
         'NAME': os.getenv('PSQL_NAME', 'dbname'),
         'USER': os.getenv('PSQL_USER', 'dbuser'),
         'PASSWORD': os.getenv('PSQL_PASSWORD', 'dbpassword'),
         'HOST': os.getenv('PSQL_HOST', 'dbhost'),
         'PORT': os.getenv('PSQL_PORT', '5432'),
         'OPTIONS': {
             'connect_timeout': 10,
         }
     } 
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True

# AWS S3 Configuration - Fixed for ACL issue
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# ✅ FIX: Disable ACL to avoid permission issues
AWS_DEFAULT_ACL = 'public-read'
AWS_S3_FILE_OVERWRITE = False
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400'
}

# Additional settings
AWS_S3_ADDRESSING_STYLE = 'virtual'
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_QUERYSTRING_AUTH = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# HTTPS Configuration for ALB setup
if not DEBUG:
    # ✅ Trust ALB SSL termination
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = False  # ALB handles SSL, don't redirect internally
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # ✅ HSTS Settings - let ALB handle this
    SECURE_HSTS_SECONDS = 0  # Disable HSTS on Django side
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    
    # ✅ Cookie security - but allow HTTP internally
    SESSION_COOKIE_SECURE = True  # Keep secure for external
    CSRF_COOKIE_SECURE = True

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/staticfiles/'

# Additional directories for staticfiles
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
] if os.path.exists(os.path.join(BASE_DIR, 'static')) else []

# Static files finders
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]


# Media files for local development (when not using S3)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = 'media/'
MEDIA_URL = f'{AWS_S3_CUSTOM_DOMAIN}/' if AWS_STORAGE_BUCKET_NAME else '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

# Configure JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=120),  # Duration for access tokens
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # Duration for refresh tokens
    'ROTATE_REFRESH_TOKENS': True,                    # Rotate refresh tokens after each use
    'BLACKLIST_AFTER_ROTATION': True,                 # Blacklist old refresh tokens
}

# Base URL untuk OpenAPI schema: pakai HTTPS di production agar Swagger UI hit https:// (hindari CORS/mixed content)
_swagger_host = (hostname or 'localhost:9002').replace('http://', '').replace('https://', '').strip()
_swagger_scheme = 'https' if (is_production or is_kong_environment) else 'http'
SWAGGER_BASE_URL = os.getenv('SWAGGER_BASE_URL', f'{_swagger_scheme}://{_swagger_host}')

# Swagger settings for JWT Authentication
SWAGGER_SETTINGS = {
    'DEFAULT_API_URL': SWAGGER_BASE_URL,
    'VALIDATOR_URL': None,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT authorization header using the Bearer scheme. \n\n'
                          'Enter \'Bearer\' [space] and then your token in the text input below.\n\n'
                          'Example: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9..."',
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': [
        'get',
        'post',
        'put',
        'delete',
        'patch'
    ],
    'OPERATIONS_SORTER': 'alpha',
    'TAGS_SORTER': 'alpha',
    'DOC_EXPANSION': 'none',
    'DEEP_LINKING': True,
    'SHOW_EXTENSIONS': True,
    'DEFAULT_MODEL_RENDERING': 'model',
}

REDOC_SETTINGS = {
    'LAZY_RENDERING': False,
}

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
