# Generated by Django 4.2 on 2025-01-13 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0001_initial'),
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wholesale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wholesales.wholesale'),
        ),
    ]
