# Generated by Django 4.2 on 2025-01-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_kodepos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodepos',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
