# Generated by Django 4.2 on 2025-02-03 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0010_alter_retailerphoto_verified_at'),
        ('wholesales', '0004_wholesaletransaction'),
        ('office', '0006_item_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimburse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reimbursed_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer.voucher')),
                ('wholesaler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesales.wholesale')),
            ],
        ),
    ]
