# Generated by Django 4.2 on 2025-02-04 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0010_alter_retailerphoto_verified_at'),
        ('office', '0007_reimburse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reimburse',
            old_name='created_by',
            new_name='reimbursed_by',
        ),
        migrations.RemoveField(
            model_name='reimburse',
            name='created_at',
        ),
        migrations.AddField(
            model_name='reimburse',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retailer.retailer'),
        ),
        migrations.AddField(
            model_name='reimburse',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('inprogress', 'In Progress'), ('closed', 'Closed')], default='pending', help_text='Status Reimburse', max_length=20),
        ),
    ]
