# Generated by Django 4.2 on 2025-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_rename_created_by_reimburse_reimbursed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimburse',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('inprogress', 'In Progress'), ('closed', 'Closed')], default='open', help_text='Status Reimburse', max_length=20),
        ),
    ]
