# Generated by Django 4.2 on 2025-02-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_alter_reimburse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimburse',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
