# Generated by Django 4.2 on 2025-02-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_reimburse_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimburse',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Payment'), ('completed', 'Payment Completed')], default='waiting', help_text='Status Reimburse', max_length=20),
        ),
    ]
