# Generated by Django 4.2 on 2025-02-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0011_alter_reimburse_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reimburse',
            old_name='closed_at',
            new_name='completed_at',
        ),
    ]
