# Generated by Django 4.2 on 2025-02-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_rename_closed_at_reimburse_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
