# Generated by Django 4.2 on 2025-02-24 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0014_alter_reimburse_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reimburse',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='reimburse',
            name='status',
        ),
        migrations.CreateModel(
            name='ReimburseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Reimburse'), ('completed', 'Reimburse Completed'), ('paid', 'Reimburse Paid')], default='waiting', help_text='Status Pembayaran', max_length=20)),
                ('status_at', models.DateTimeField(blank=True, null=True)),
                ('status_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reimburse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.reimburse')),
            ],
        ),
    ]
