# Generated by Django 4.2 on 2025-02-24 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0015_remove_reimburse_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reimbursestatus',
            name='reimburse',
        ),
        migrations.AddField(
            model_name='reimburse',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reimburses', to='office.reimbursestatus'),
        ),
    ]
