# Generated by Django 4.2 on 2025-02-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0016_remove_reimbursestatus_reimburse_reimburse_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=0)),
                ('current_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
