# Generated by Django 4.2 on 2025-02-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0017_voucherlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherlimit',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
