# Generated by Django 5.1.3 on 2025-01-10 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wholesale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherRedeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer.voucher')),
                ('wholesaler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesales.wholesale')),
            ],
        ),
    ]
