# Generated by Django 4.2 on 2025-01-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesale',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Status aktif atau tidaknya wholesales'),
        ),
    ]
