# Generated by Django 4.2 on 2025-01-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0002_wholesale_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesale',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wholesale',
            name='pic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
