# Generated by Django 4.2 on 2025-02-14 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_alter_item_sku'),
        ('wholesales', '0004_wholesaletransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaletransaction',
            name='rym_qty',
        ),
        migrations.RemoveField(
            model_name='wholesaletransaction',
            name='ryp_qty',
        ),
        migrations.RemoveField(
            model_name='wholesaletransaction',
            name='rys_qty',
        ),
        migrations.CreateModel(
            name='WholesaleTransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_transaction_details', to='office.item')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesales.wholesaletransaction')),
            ],
        ),
    ]
