# Generated by Django 4.2 on 2025-02-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0005_remove_wholesaletransaction_rym_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesale',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
