# Generated by Django 4.2 on 2025-03-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0006_wholesale_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesale',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
