# Generated by Django 4.2 on 2025-07-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0007_wholesale_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wholesale',
            options={'verbose_name': 'Wholesale', 'verbose_name_plural': 'Wholesales'},
        ),
        migrations.AddField(
            model_name='wholesale',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent wholesale untuk struktur hierarki', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wholesales.wholesale'),
        ),
    ]
