# Generated by Django 4.2 on 2025-07-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesales', '0008_alter_wholesale_options_wholesale_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
