# Generated by Django 4.2 on 2025-07-29 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0019_voucherproject_voucherretailerdiscount_and_more'),
        ('wholesales', '0009_alter_wholesale_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesale',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.voucherproject'),
        ),
    ]
